Auto upload assets (#113)
* Bump to v2.0.0-SNAPSHOT

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* Upload asset to release

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* typo

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* replace deprecated github command + change path of file to upload

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct file name

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct file name ubuntu

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* Run workflow when a release has been published

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* replace deprecated GitHub command

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* cancel duplicate workflows

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* add specific job to release assets if QA is successful

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct condition on job needed to continue

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* cancel duplicated workflows

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* cancel duplicated workflows

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* add job specific to release ubuntu assets

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct paths

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* clang-tidy only on PR

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct folder for build

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* add default shell

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* add Clang Tidy on Release + correct ubuntu conf for asset upload

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test to find path for files

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* typo

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct files search for clang-tidy in release

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* export clang-tidy report as .txt

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test clang-tidy with error message

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test search for newer versions of clang

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test search for newer versions of clang

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test update clang-tidy

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test update clang-tidy

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test update clang-tidy

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test update clang-tidy and search

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test update clang-tidy from web link

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test update clang-tidy from web link

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* test update clang-tidy from web link

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* reset clang-tidy

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* deactivate Clang-Tidy checks for release and workflows_dispatch

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* update clang-tidy on ubuntu

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* delete useless command

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* reactivate clang on ubuntu

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct report paths

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* correct report paths

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

* add true to continue CI

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

---------

Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

(cherry picked from commit e8864f3f655356d8ddf8a5171f371a6d23c3cb76)
Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

diff --git a/.github/workflows/qa_pr_cpp_centos7.yml b/.github/workflows/qa_pr_cpp_centos7.yml
--- a/.github/workflows/qa_pr_cpp_centos7.yml
+++ b/.github/workflows/qa_pr_cpp_centos7.yml
@@ -5,7 +5,14 @@ on:
   pull_request:
     types: [opened, ready_for_review, reopened]
   release:
-    types: [created, published, released]
+    types: [published]
+
+# Cancel previous workflows if they are the same workflow on same ref (branch/tags)
+# with the same event (push/pull_request) even they are in progress.
+# This setting will help reduce the number of duplicated workflows.
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
+  cancel-in-progress: true
 
 jobs:
   clang-tidy:
@@ -59,13 +66,51 @@ jobs:
           source /opt/rh/devtoolset-9/enable
           cmake -S $GITHUB_WORKSPACE/metrix-simulator -B $GITHUB_WORKSPACE/metrix-simulator/build-centos7 -DCMAKE_BUILD_TYPE=Debug -DBoost_ROOT=$GITHUB_WORKSPACE/__w/Boost/Boost/boost_1_73_0/installBoost -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
 
-      - name: Clang Tidy
+      - name: Clang Tidy PR
+        id: clang-pr
+        if: github.event_name == 'pull_request'
         run: |
+          REPORT_NAME="clang_tidy_report_centos.txt"
+          REPORT_PATH="$PWD/${REPORT_NAME}"
           export MODIFIED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }} origin/${{ github.head_ref }}  | grep -E ".*(metrix-simulator/src|metrix-simulator/log).*\.(cpp|hpp)$")
-          echo $MODIFIED_FILES
           if [ -n "$MODIFIED_FILES" ]; then
-              clang-tidy $MODIFIED_FILES -p $GITHUB_WORKSPACE/metrix-simulator/build-centos7
+              clang-tidy $MODIFIED_FILES -p $GITHUB_WORKSPACE/metrix-simulator/build-centos7 > $REPORT_NAME || true
           fi
+          echo "report_name=$REPORT_NAME" >> "$GITHUB_OUTPUT"
+          echo "report_path=$REPORT_PATH" >> "$GITHUB_OUTPUT"
+
+      - name: Upload Clang Tidy report - PR
+        if: github.event_name == 'pull_request'
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ steps.clang-pr.outputs.report_name }}
+          path: ${{ steps.clang-pr.outputs.report_path }}
+
+#      - name: Clang Tidy Release
+#        id: clang-release
+#        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
+#        run: |
+#          REPORT_NAME="clang_tidy_report_centos.txt"
+#          REPORT_PATH="$PWD/${REPORT_NAME}"
+#          export MODIFIED_FILES=$(find metrix-simulator/log/ metrix-simulator/src/ -type f | grep -E ".*(metrix-simulator/src|metrix-simulator/log).*\.(cpp|hpp)$")
+#          if [ -n "$MODIFIED_FILES" ]; then
+#              clang-tidy $MODIFIED_FILES -p $GITHUB_WORKSPACE/metrix-simulator/build > $REPORT_NAME || true
+#              cat clan_tidy_report_centos.txt  # Display the contents of the report
+#              exit_code=$?
+#              if [ $exit_code -ne 0 ]; then
+#                  echo "clang-tidy failed with exit code $exit_code"
+#                  exit $exit_code
+#              fi
+#          fi
+#          echo "report_name=$REPORT_NAME" >> "$GITHUB_OUTPUT"
+#          echo "report_path=$REPORT_PATH" >> "$GITHUB_OUTPUT"
+#
+#      - name: Upload Clang Tidy report - Release
+#        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: ${{ steps.clang-release.outputs.report_name }}
+#          path: ${{ steps.clang-release.outputs.report_path }}
 
   qa:
     name: Full QA C++ CentOS
@@ -159,24 +204,74 @@ jobs:
           cd metrix-simulator
           /__w/powsybl-metrix/sonar/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io
 
+  release:
+    name: Release CentOS7
+    runs-on: ubuntu-latest
+    container: 'centos:centos7'
+    needs: qa
+    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
+    steps:
+      - name: Install Dependencies
+        run: |
+          yum update -y
+          yum install -y epel-release
+          yum install -y git redhat-lsb-core make wget centos-release-scl scl-utils
+          yum install -y devtoolset-9
+
+      - name: Setup cmake
+        uses: jwlawson/actions-setup-cmake@v1.13
+        with:
+          cmake-version: '3.22.x'
+
+      - name: Checkout sources
+        uses: actions/checkout@v1
+
+      - name: Download Boost-release
+        uses: dsaltares/fetch-gh-release-asset@master
+        with:
+          repo: 'ARnDOSrte/Boost'
+          file: 'boost_1_73_0.zip'
+          target: 'boost_1_73_0.zip'
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Unzip Boost
+        run: unzip boost_1_73_0.zip
+
+      - name: Configure 3rd parties
+        run: |
+          source /opt/rh/devtoolset-9/enable
+          cmake -S $GITHUB_WORKSPACE/metrix-simulator/external -B $GITHUB_WORKSPACE/metrix-simulator/build/external
+
+      - name: Build 3rd parties
+        run: |
+          cmake --build $GITHUB_WORKSPACE/metrix-simulator/build/external --parallel 2
+
+      - name: Configure CMake
+        run: |
+          source /opt/rh/devtoolset-9/enable
+          cmake -S $GITHUB_WORKSPACE/metrix-simulator -Wno-dev -DCMAKE_BUILD_TYPE=Release -DBoost_ROOT=$GITHUB_WORKSPACE/__w/Boost/Boost/boost_1_73_0/installBoost -DBoost_INCLUDE_DIR=$GITHUB_WORKSPACE/__w/Boost/Boost/boost_1_73_0/installBoost -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/metrix-simulator/build/install -B $GITHUB_WORKSPACE/metrix-simulator/build
+
+      - name: Build
+        run: cmake --build $GITHUB_WORKSPACE/metrix-simulator/build --target install --parallel 2
+
       - name: Prepare Metrix install
-        if: |
-          github.event_name == 'release' ||
-          github.event_name == 'workflow_dispatch'
         id: metrix-install
         run: |
-          ARCHIVE_NAME="metrix-simulator-centos7.zip"
+          ARCHIVE_NAME="metrix-simulator-centos7"
           ARCHIVE_PATH="$PWD/${ARCHIVE_NAME}"
           cd metrix-simulator/build/install/
           zip -r $ARCHIVE_PATH bin etc
-          echo "::set-output name=archive_name::$ARCHIVE_NAME"
-          echo "::set-output name=archive_path::$ARCHIVE_PATH"
+          echo "archive_name=$ARCHIVE_NAME" >> "$GITHUB_OUTPUT"
+          echo "archive_path=$ARCHIVE_PATH" >> "$GITHUB_OUTPUT"
 
       - name: Upload OR-Tools install artifact
-        if: |
-          github.event_name == 'release' ||
-          github.event_name == 'workflow_dispatch'
         uses: actions/upload-artifact@v3
         with:
-          name: ${{ steps.metrix-install.outputs.archive_name }}
-          path: ${{ steps.metrix-install.outputs.archive_path }}
+          name: ${{ steps.metrix-install.outputs.archive_name }}.zip
+          path: ${{ steps.metrix-install.outputs.archive_path }}.zip
+
+      - name: Upload asset to release
+        uses: softprops/action-gh-release@v1
+        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
+        with:
+          files: ${{ steps.metrix-install.outputs.archive_name }}.zip
