update clang-tidy on ubuntu
Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

diff --git a/.github/workflows/qa_pr_cpp_ubuntu.yml b/.github/workflows/qa_pr_cpp_ubuntu.yml
--- a/.github/workflows/qa_pr_cpp_ubuntu.yml
+++ b/.github/workflows/qa_pr_cpp_ubuntu.yml
@@ -30,8 +30,8 @@ jobs:
 
       - name: Install clang-tidy
         run: |
-          sudo apt install -y clang-tidy-14
-          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-14 100
+          sudo apt install -y clang-tidy-15
+          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-15 100
 
       - name: Checkout sources
         uses: actions/checkout@v1
@@ -63,10 +63,17 @@ jobs:
         run: |
           export MODIFIED_FILES=$(find metrix-simulator/log/ metrix-simulator/src/ -type f | grep -E ".*(metrix-simulator/src|metrix-simulator/log).*\.(cpp|hpp)$")
           if [ -n "$MODIFIED_FILES" ]; then
-              clang-tidy $MODIFIED_FILES -p $GITHUB_WORKSPACE/metrix-simulator/build > clan_tidy_report.txt
+              clang-tidy $MODIFIED_FILES -p $GITHUB_WORKSPACE/metrix-simulator/build > clan_tidy_report.txt || true
+              cat clan_tidy_report.txt  # Display the contents of the report
+              exit_code=$?
+              if [ $exit_code -ne 0 ]; then
+                  echo "clang-tidy failed with exit code $exit_code"
+                  exit $exit_code
+              fi
           fi
 
       - name: Upload OR-Tools install artifact
+        if: github.event_name == 'pull_request'
         uses: actions/upload-artifact@v3
         with:
           name: clan_tidy_report.txt
