test clang-tidy with error message
Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

diff --git a/.github/workflows/qa_pr_cpp_centos7.yml b/.github/workflows/qa_pr_cpp_centos7.yml
--- a/.github/workflows/qa_pr_cpp_centos7.yml
+++ b/.github/workflows/qa_pr_cpp_centos7.yml
@@ -79,7 +79,13 @@ jobs:
         run: |
           export MODIFIED_FILES=$(find metrix-simulator/log/ metrix-simulator/src/ -type f | grep -E ".*(metrix-simulator/src|metrix-simulator/log).*\.(cpp|hpp)$")
           if [ -n "$MODIFIED_FILES" ]; then
-              clang-tidy $MODIFIED_FILES -p $GITHUB_WORKSPACE/metrix-simulator/build > clan_tidy_report.txt
+              clang-tidy $MODIFIED_FILES -p $GITHUB_WORKSPACE/metrix-simulator/build > clan_tidy_report.txt || true
+              cat clan_tidy_report.txt  # Display the contents of the report
+              exit_code=$?
+              if [ $exit_code -ne 0 ]; then
+                  echo "clang-tidy failed with exit code $exit_code"
+                  exit $exit_code
+              fi
           fi
 
       - name: Upload OR-Tools install artifact
