fix status
Signed-off-by: Nicolas Rol <nicolas.rol@rte-france.com>

diff --git a/.github/workflows/snapshot-ci.yml b/.github/workflows/snapshot-ci.yml
--- a/.github/workflows/snapshot-ci.yml
+++ b/.github/workflows/snapshot-ci.yml
@@ -157,61 +157,45 @@ jobs:
             powsybl-metrix/metrix-simulator/build/install/bin
             powsybl-metrix/metrix-simulator/build/install/etc
 
-#      - name: Record Job Name
-#        if: failure()
-#        run: |
-#          echo "❌ Failed job : Build powsybl-metrix on ${{ matrix.os }}" >> $BUILD_STATUS
-#
-#      - name: Read Build Status
-#        if: always()
-#        id: build_status
-#        run: |
-#          echo "=== BUILD STATUS REPORT ==="
-#          cat $BUILD_STATUS
-#          echo "=========================="
-#          echo "BUILD_STATUS_CONTENT<<EOF" >> $GITHUB_OUTPUT
-#          cat $BUILD_STATUS >> $GITHUB_OUTPUT
-#          echo "EOF" >> $GITHUB_OUTPUT
-
       - name: Update job results
         if: always()
         run: |
           echo "JOB_RESULTS=${{ env.JOB_RESULTS }}${{ matrix.os }}:${{ job.status }};" >> $GITHUB_ENV
+
+      - name: Store job result
+        if: always()
+        run: |
+          echo "${{ matrix.os }}=${{ job.status }}" >> $GITHUB_OUTPUT
+        id: job_result
+
+    outputs:
+      matrix-result: ${{ toJSON(steps.job_result.outputs) }}
 
   # Slack notification on failure
   notify_slack:
     needs: build_powsybl_metrix
     runs-on: ubuntu-latest
     if: always()
-#    steps:
-#      - name: Send Slack Notification
-#        uses: 8398a7/action-slack@28ba43ae48961b90635b50953d216767a6bea486 # v3.16.2
-#        with:
-#          author_name: 'powsybl-metrix on GitHub'
-#          status: ${{ job.status }}
-#          text: |
-#            :x: *Failed workflow ${{ github.workflow }}*
-#            *Failure details:*
-#            ```
-#            ${{ needs.build_powsybl_metrix.outputs.build_status }}
-#            ```
-#            See logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-#        env:
-#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
     steps:
+      - name: Determine workflow status
+        id: workflow_status
+        run: |
+          if [ "${{ job.status }}" == "success" ]; then
+            echo "icon=✅" >> $GITHUB_OUTPUT
+            echo "status=Successful" >> $GITHUB_OUTPUT
+          else
+            echo "icon=❌" >> $GITHUB_OUTPUT
+            echo "status=Failed" >> $GITHUB_OUTPUT
+          fi
+
       - name: Format job results
         id: format_results
         run: |
+          results='${{ needs.build.outputs.matrix-result }}'
           formatted=""
-          IFS=';' read -ra RESULTS <<< "${{ env.JOB_RESULTS }}"
-          for result in "${RESULTS[@]}"; do
-            if [[ ! -z "$result" ]]; then
-              IFS=':' read -ra PARTS <<< "$result"
-              os="${PARTS[0]}"
-              status="${PARTS[1]}"
-              icon=$([ "$status" == "success" ] && echo ":white_check_mark:" || echo ":x:")
-              formatted+="${icon} Build powsybl-metrix on *${os}*\n"
-            fi
+          echo "$results" | jq -r 'to_entries[] | .key + "=" + .value' | while IFS='=' read -r os status; do
+            icon=$([ "$status" == "success" ] && echo ":white_check_mark:" || echo ":x:")
+            formatted+="${icon} Build powsybl-metrix on *${os}*\n"
           done
           echo "formatted_results<<EOF" >> $GITHUB_OUTPUT
           echo -e "$formatted" >> $GITHUB_OUTPUT
@@ -225,13 +209,13 @@ jobs:
           custom_payload: |
             {
               attachments: [{
-                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
+                color: '${{ job.status }}' === 'success' ? "#319f4b" : '${{ job.status }}' === 'failure' ? "#f64538" : "#ffc965",
                 "blocks": [
                   {
                     "type": "section",
                     "text": {
                       "type": "mrkdwn",
-                      "text": "❌ *Failed workflow: Snapshot-CI on <https://github.com/powsybl/powsybl-metrix|powsybl-metrix>*"
+                      "text": "${{ steps.workflow_status.outputs.icon }} *${{ steps.workflow_status.outputs.status }} workflow: Snapshot-CI on <https://github.com/powsybl/powsybl-metrix|powsybl-metrix>*"
                     }
                   },
                   {
